# Generated by Django 3.1.4 on 2020-12-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
