# Generated by Django 3.1.4 on 2020-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201217_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='important',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('None', 'None')], max_length=6),
        ),
    ]
